#ifndef TEST_BINARY_SEARCH_RECURSIVE_H
#define TEST_BINARY_SEARCH_RECURSIVE_H

void shouldReturnCorrectPositionAndValue_Recursive(void);
void shouldReturnNegativePositionAndValueIfValueNotFound_Recursive(void);
void shouldReturnNegativePositionAndValueIfArrayEmpty_Recursive(void);
void shouldReturnNegativePositionAndValueIfArrayNULL_Recursive(void);
void shouldReturnZero_Recursive(void);

#endif // !TEST_BINARY_SEARCH_RECURSIVE_H
